### ISSUE TITLE
Interpretation of * character in paf file output

### ISSUE THREAD

**Issue by daanishmahajan** [CMU-SAFARI/RawHash#8]
Hi @canfirtina,

Can you please tell, what * character in the paf file output means?

Example:

```

S1_7!chr21_MATERNAL!39635639!39638070!- 2699    *       *       *       *       *       *       *       *       *       0       mt:f:5.954981  ci:i:6  sl:i:21821      cm:i:2  nc:i:1  s1:i:19 sm:f:0.00
```

**Comment by canfirtina** [comment]
Hi @daanishmahajan,

It means the read is unmapped.

More information about the PAF format RawHash uses can be found here: https://github.com/lh3/miniasm/blob/master/PAF.md and here: https://github.com/skovaka/UNCALLED?tab=readme-ov-file#output-format

**Comment by daanishmahajan** [comment]
Hi @canfirtina,
I wanted to confirm that the mapping quality is denoted by the `cm` identifier, right?
Thanks

**Comment by canfirtina** [comment]
Hi @daanishmahajan,

`cm` tag shows the number of anchors in the chain `chains[c_id].cnt` that RawHash2 uses to report the mapping information for a read:
https://github.com/CMU-SAFARI/RawHash/blob/44fe7a322696c23bcb49024871f2c7e2a8d6fdbf/src/rmap.cpp#L550

The mapping quality is stored here:
https://github.com/CMU-SAFARI/RawHash/blob/44fe7a322696c23bcb49024871f2c7e2a8d6fdbf/src/rmap.cpp#L565

And outputted here (12th column in the PAF file): https://github.com/CMU-SAFARI/RawHash/blob/44fe7a322696c23bcb49024871f2c7e2a8d6fdbf/src/rmap.cpp#L747
